/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Almacenes.Almacen_Jugadores;
import GUI.VAdmin;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Personas.Jugador;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author a.tercero.2020
 */
public class VEditJugador extends javax.swing.JFrame {

    int x, y;
    Almacen_Jugadores aJugadores;
    VAdmin vAdmin;

    /**
     * Creates new form VEditJugador
     */
    public VEditJugador(VAdmin vAdmin, Almacen_Jugadores aJugadores) {
        initComponents();
        this.setLocationRelativeTo(vAdmin);
        this.vAdmin = vAdmin;
        this.aJugadores = aJugadores;

        resetJugadores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iSalir = new javax.swing.JLabel();
        iCabecera = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cListaJugadores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tClave = new javax.swing.JTextField();
        bAddJugador = new javax.swing.JButton();
        bEditUsuario = new javax.swing.JButton();
        bBorrarJugador = new javax.swing.JButton();
        bEditClave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tUsuarioChange = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tNewClave = new javax.swing.JTextField();
        iFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Boton_salir.png"))); // NOI18N
        iSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSalirMouseClicked(evt);
            }
        });
        getContentPane().add(iSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        iCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Cabecera.png"))); // NOI18N
        iCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                iCabeceraMouseDragged(evt);
            }
        });
        iCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(iCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Lista de jugadores:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cListaJugadores.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        cListaJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cListaJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(cListaJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 140, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        tUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(tUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Nueva Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        tClave.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(tClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 230, -1));

        bAddJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bAddJugador.setText("Añadir Jugador");
        bAddJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddJugadorMouseClicked(evt);
            }
        });
        bAddJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(bAddJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, -1));

        bEditUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bEditUsuario.setText("Editar Usuario");
        bEditUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditUsuarioMouseClicked(evt);
            }
        });
        bEditUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(bEditUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 210, -1));

        bBorrarJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bBorrarJugador.setText("Eliminar Jugador");
        bBorrarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBorrarJugadorMouseClicked(evt);
            }
        });
        getContentPane().add(bBorrarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 210, -1));

        bEditClave.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bEditClave.setText("Editar Contraseña");
        bEditClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditClaveMouseClicked(evt);
            }
        });
        getContentPane().add(bEditClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 210, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        tUsuarioChange.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(tUsuarioChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 220, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Nuevo Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        tNewClave.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        getContentPane().add(tNewClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 210, -1));

        iFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/489.jpg"))); // NOI18N
        getContentPane().add(iFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetJugadores() {
        cListaJugadores.removeAllItems();
        for (int i = 0; i < aJugadores.sizeJugadores(); i++) {
            cListaJugadores.addItem(aJugadores.getJugador(i).getNombre());
        }
    }

    private void iSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        vAdmin.setVisible(true);

    }//GEN-LAST:event_iSalirMouseClicked

    private void iCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_iCabeceraMouseDragged

    private void iCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_iCabeceraMousePressed

    private void tUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsuarioActionPerformed

    private void bAddJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddJugadorActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_bAddJugadorActionPerformed

    private void cListaJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cListaJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cListaJugadoresActionPerformed

    private void bEditUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditUsuarioActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_bEditUsuarioActionPerformed

    private void bAddJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddJugadorMouseClicked
        // TODO add your handling code here:

        String Usuario = tUsuario.getText();
        String Clave = tClave.getText();

        boolean encontrado = false;

        for (int i = 0; i < aJugadores.sizeJugadores(); i++) {
            String jugador = aJugadores.getJugador(i).getNombre();
            if (jugador.equals(Usuario)) {
                encontrado = true;
            }
        }

        if (Usuario.equals("") || Clave.equals("")) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Debe rellenar los dos campos");

        } else if (encontrado == true) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "El nombre de Usuario ya está en uso");

        } else {
            Jugador jugador = new Jugador(Usuario, Clave);
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Jugador añadido con éxito");

            aJugadores.addJugador(jugador);
            cListaJugadores.addItem(Usuario);
            resetJugadores();
        }

    }//GEN-LAST:event_bAddJugadorMouseClicked

    private void bEditUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditUsuarioMouseClicked

        // TODO add your handling code here:
        String usuario = tUsuario.getText();
        String clave = tClave.getText();

        String nuevo = tUsuarioChange.getText();

        boolean encontrado = false;
        boolean nuevoRepe = false;
        int j = 0;

        for (int i = 0; i < aJugadores.sizeJugadores(); i++) {
            String jugador = aJugadores.getJugador(i).getNombre();
            if (jugador.equals(usuario)) {
                encontrado = true;
                j = i;
            }

        }

        for (int i = 0; i < aJugadores.sizeJugadores(); i++) {
            String jugador = aJugadores.getJugador(i).getNombre();
            if (jugador.equals(nuevo)) {
                nuevoRepe = true;
            }
        }

        if (usuario.equals("") || encontrado == false) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Debe ser un usuario existente");
        } else if (nuevoRepe == true) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "El nombre nuevo ya existe");

        } else {

            aJugadores.getJugador(j).setNombre(nuevo);

            resetJugadores();
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Usuario editado con éxito.");
        }
    }//GEN-LAST:event_bEditUsuarioMouseClicked

    private void bBorrarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBorrarJugadorMouseClicked
        // TODO add your handling code here:

        String usuario = tUsuario.getText();

        boolean encontrado = false;
        Jugador j = null;

        for (int i = 0; i < aJugadores.sizeJugadores(); i++) {
            String jugador = aJugadores.getJugador(i).getNombre();
            if (jugador.equals(usuario)) {
                encontrado = true;
                j = aJugadores.getJugador(i);
            }

        }
        if (usuario.equals("") || encontrado == false) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Debe ser un usuario existente");

        } else {

            aJugadores.removeJugador(j);

            resetJugadores();
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Jugador eliminado con éxito");
        }


    }//GEN-LAST:event_bBorrarJugadorMouseClicked

    private void bEditClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditClaveMouseClicked
        // TODO add your handling code here:
        String usuario = tUsuario.getText();

        String nuevo = tNewClave.getText();

        boolean encontrado = false;
        boolean nuevoRepe = false;

        int j = 0;

        for (int i = 0; i < aJugadores.sizeJugadores(); i++) {
            String jugador = aJugadores.getJugador(i).getNombre();
            if (jugador.equals(usuario)) {
                encontrado = true;
                j = i;
                String contra = aJugadores.getJugador(i).getContraseña();
                if (contra.equals(nuevo)) {
                    nuevoRepe = true;
                }
            }

        }

        if (usuario.equals("") || encontrado == false) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Debe ser un usuario existente");

        } else if (nuevoRepe == true) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "La contraseña ya esta en uso");

        } else {

            aJugadores.getJugador(j).setContraseña(nuevo);
            resetJugadores();
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Contraseña cambiada con éxito");

        }
    }//GEN-LAST:event_bEditClaveMouseClicked
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("GUI_Images/icono.png"));
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddJugador;
    private javax.swing.JButton bBorrarJugador;
    private javax.swing.JButton bEditClave;
    private javax.swing.JButton bEditUsuario;
    private javax.swing.JComboBox<String> cListaJugadores;
    private javax.swing.JLabel iCabecera;
    private javax.swing.JLabel iFondo;
    private javax.swing.JLabel iSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tClave;
    private javax.swing.JTextField tNewClave;
    private javax.swing.JTextField tUsuario;
    private javax.swing.JTextField tUsuarioChange;
    // End of variables declaration//GEN-END:variables
}
