/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Almacenes.Almacen_Palabras;
import Componentes_Rosco.Definicion;
import Componentes_Rosco.Palabra;
import GUI.VAdmin;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author e.tamajon.2020
 */
public class VEditPalabra extends javax.swing.JFrame {

    int x, y;

    VAdmin vAdmin;
    Almacen_Palabras aPalabras;

    /**
     * Creates new form VEditPalabra
     */
    public VEditPalabra(VAdmin vAdmin, Almacen_Palabras aPalabras) {
        initComponents();
        this.setLocationRelativeTo(vAdmin);
        this.vAdmin = vAdmin;
        this.aPalabras = aPalabras;

        resetPalabras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iSalir = new javax.swing.JLabel();
        iCabecera = new javax.swing.JLabel();
        jLista = new javax.swing.JLabel();
        jLista1 = new javax.swing.JLabel();
        cPalabras = new javax.swing.JComboBox<>();
        jText = new javax.swing.JLabel();
        tPalabra = new javax.swing.JTextField();
        tDefinicion = new javax.swing.JTextField();
        bAñadirPalabra = new javax.swing.JButton();
        bEliminarPalabra = new javax.swing.JButton();
        bEditarPalabra = new javax.swing.JButton();
        bAñadirDefinicion = new javax.swing.JButton();
        bEditarDefinicion = new javax.swing.JButton();
        bEliminarDefinicion = new javax.swing.JButton();
        cDefiniciones = new javax.swing.JComboBox<>();
        jText1 = new javax.swing.JLabel();
        iFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Boton_salir.png"))); // NOI18N
        iSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSalirMouseClicked(evt);
            }
        });
        getContentPane().add(iSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        iCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Cabecera.png"))); // NOI18N
        iCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                iCabeceraMouseDragged(evt);
            }
        });
        iCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(iCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 830, -1));

        jLista.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLista.setText("Lista de palabras:");
        getContentPane().add(jLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLista1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLista1.setText("Definiciones:");
        getContentPane().add(jLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        cPalabras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cPalabras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cPalabrasMouseClicked(evt);
            }
        });
        getContentPane().add(cPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, 30));

        jText.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jText.setText("Palabra:");
        getContentPane().add(jText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        tPalabra.setBackground(new java.awt.Color(102, 102, 102));
        tPalabra.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tPalabra.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 490, 30));

        tDefinicion.setBackground(new java.awt.Color(102, 102, 102));
        tDefinicion.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tDefinicion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tDefinicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 490, 30));

        bAñadirPalabra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bAñadirPalabra.setText("Añadir palabra");
        bAñadirPalabra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAñadirPalabraMouseClicked(evt);
            }
        });
        getContentPane().add(bAñadirPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 490, 30));

        bEliminarPalabra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bEliminarPalabra.setText("Eliminar palabra");
        bEliminarPalabra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEliminarPalabraMouseClicked(evt);
            }
        });
        getContentPane().add(bEliminarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 490, -1));

        bEditarPalabra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bEditarPalabra.setText("Editar palabra");
        bEditarPalabra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditarPalabraMouseClicked(evt);
            }
        });
        getContentPane().add(bEditarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 490, 30));

        bAñadirDefinicion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bAñadirDefinicion.setText("Añadir definición");
        bAñadirDefinicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAñadirDefinicionMouseClicked(evt);
            }
        });
        getContentPane().add(bAñadirDefinicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 490, 30));

        bEditarDefinicion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bEditarDefinicion.setText("Editar definición");
        bEditarDefinicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditarDefinicionMouseClicked(evt);
            }
        });
        getContentPane().add(bEditarDefinicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 490, 30));

        bEliminarDefinicion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bEliminarDefinicion.setText("Eliminar definición");
        bEliminarDefinicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEliminarDefinicionMouseClicked(evt);
            }
        });
        getContentPane().add(bEliminarDefinicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 490, -1));

        cDefiniciones.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cDefiniciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cDefinicionesMouseClicked(evt);
            }
        });
        getContentPane().add(cDefiniciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 320, 30));

        jText1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jText1.setText("Definición:");
        getContentPane().add(jText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        iFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/489.jpg"))); // NOI18N
        getContentPane().add(iFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_iCabeceraMouseDragged

    private void iCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_iCabeceraMousePressed

    private void iSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        vAdmin.setVisible(true);
    }//GEN-LAST:event_iSalirMouseClicked

    private void bAñadirPalabraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAñadirPalabraMouseClicked
        // TODO add your handling code here:
        String palabraString = tPalabra.getText();
        String definicion = tDefinicion.getText();

        if (palabraString.equals("") || definicion.equals("")) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Debe rellenar la palabra y la definición.");
        } else {
            Palabra palabra = new Palabra(palabraString);
            palabra.addDefinicion(definicion);

            aPalabras.addPalabra(palabra);
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Palabra añadida.");
            resetPalabras();

        }
    }//GEN-LAST:event_bAñadirPalabraMouseClicked

    private void bEliminarPalabraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEliminarPalabraMouseClicked
        String palabraString = (String) cPalabras.getSelectedItem();
        Palabra palabraEliminar = aPalabras.getPalabra(palabraString);

        JFrame jFrame = new JFrame();
        if (aPalabras.remove(palabraEliminar)) {
            JOptionPane.showMessageDialog(jFrame, "Palabra eliminada.");
            resetPalabras();
        } else {
            JOptionPane.showMessageDialog(jFrame, "Palabra no eliminada.");
        }
    }//GEN-LAST:event_bEliminarPalabraMouseClicked

    private void bEditarPalabraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarPalabraMouseClicked
        // TODO add your handling code here:
        String palabraString = (String) cPalabras.getSelectedItem();
        Palabra palabra = aPalabras.getPalabra(palabraString);

        String palabraSustituir = tPalabra.getText();

        if (palabraSustituir.equals("")) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Debe insertar una palabra.");
        } else {
            if (palabraString.equals(palabra.toString())) {
                aPalabras.sustituirPalabra(palabra, palabraSustituir);
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Palabra editada.");
                resetPalabras();
            }
        }

    }//GEN-LAST:event_bEditarPalabraMouseClicked

    private void cDefinicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cDefinicionesMouseClicked
        resetDefiniciones();
    }//GEN-LAST:event_cDefinicionesMouseClicked

    private void bAñadirDefinicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAñadirDefinicionMouseClicked
        // TODO add your handling code here:
        String definicion = tDefinicion.getText();

        String palabraString = (String) cPalabras.getSelectedItem();
        Palabra palabra = aPalabras.getPalabra(palabraString);

        if (definicion.equals("")) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Debe insertar una definición.");
        } else {
            aPalabras.getPalabra(palabraString).addDefinicion(definicion);
            cDefiniciones.addItem(definicion);
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Definición añadida.");
            resetDefiniciones();
        }
    }//GEN-LAST:event_bAñadirDefinicionMouseClicked

    private void bEditarDefinicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarDefinicionMouseClicked
        // TODO add your handling code here:
        String definicion = tDefinicion.getText();
        int index = cDefiniciones.getSelectedIndex();

        String palabraString = (String) cPalabras.getSelectedItem();
        Palabra palabra = aPalabras.getPalabra(palabraString);

        if (definicion.equals("")) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Debe insertar una definición.");
        } else {
            aPalabras.getPalabra(palabraString).editDefinicion(definicion, index);
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Definición editada.");
            resetDefiniciones();
        }
    }//GEN-LAST:event_bEditarDefinicionMouseClicked

    private void bEliminarDefinicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEliminarDefinicionMouseClicked
        // TODO add your handling code here:

        String definicionString = (String) cDefiniciones.getSelectedItem();
        String palabraString = (String) cPalabras.getSelectedItem();

        Palabra palabra = aPalabras.getPalabra(palabraString);

        Definicion definicion = new Definicion(definicionString);
        aPalabras.getPalabra(palabraString).getDefiniciones().remove(definicion);

        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, "Definición eliminada.");
        resetDefiniciones();

    }//GEN-LAST:event_bEliminarDefinicionMouseClicked

    private void cPalabrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cPalabrasMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cPalabrasMouseClicked

    private void resetDefiniciones() {
        cDefiniciones.removeAllItems();

        String palabraString = (String) cPalabras.getSelectedItem();
        Palabra palabra = aPalabras.getPalabra(palabraString);

        for (int i = 0; i < palabra.sizeDefiniciones(); i++) {
            String definicion = palabra.getDefiniciones().get(i).getDefinicion();
            cDefiniciones.addItem(definicion);
        }
    }

    private void resetPalabras() {
        cPalabras.removeAllItems();

        for (int i = 0; i < aPalabras.sizeAlmacen(); i++) {
            for (int j = 0; j < aPalabras.sizeAlmacenLetra(i); j++) {
                Palabra p = aPalabras.getPalabra(i, j);
                cPalabras.addItem(p.toString());
            }
        }

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("GUI_Images/icono.png"));
        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadirDefinicion;
    private javax.swing.JButton bAñadirPalabra;
    private javax.swing.JButton bEditarDefinicion;
    private javax.swing.JButton bEditarPalabra;
    private javax.swing.JButton bEliminarDefinicion;
    private javax.swing.JButton bEliminarPalabra;
    private javax.swing.JComboBox<String> cDefiniciones;
    private javax.swing.JComboBox<String> cPalabras;
    private javax.swing.JLabel iCabecera;
    private javax.swing.JLabel iFondo;
    private javax.swing.JLabel iSalir;
    private javax.swing.JLabel jLista;
    private javax.swing.JLabel jLista1;
    private javax.swing.JLabel jText;
    private javax.swing.JLabel jText1;
    private javax.swing.JTextField tDefinicion;
    private javax.swing.JTextField tPalabra;
    // End of variables declaration//GEN-END:variables
}
