/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Almacenes.Almacen_Palabras;
import Componentes_Rosco.Palabra;
import Componentes_Rosco.Rosco;
import Personas.Administrador;
import Personas.Jugador;
import Tipos_de_Juego.Entrenamiento;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author e.tamajon.2020
 */
public class VEntrenamiento extends javax.swing.JFrame {

    int x, y;

    VJugador vJugador;
    VAdmin vAdmin;

    Palabra palabraActual;
    Administrador administrador;

    Entrenamiento entrenamiento;
    Almacen_Palabras aPalabras;

    /**
     * Creates new form VEntrenamiento
     */
    public VEntrenamiento(VJugador vJugador, Jugador jugador, int numPal, Almacen_Palabras aPalabras) {
        initComponents();
        this.setLocationRelativeTo(vJugador);

        JFrame jFrame;

        this.vJugador = vJugador;

        this.aPalabras = aPalabras;

        entrenamiento = new Entrenamiento(jugador, numPal, aPalabras);

        tNombreJ.setText(jugador.getNombre());
        tPuntos.setText(String.valueOf(jugador.getPuntos()));
        tFallos.setText("0");
        tPuntosPartida.setText("0");

        tVueltas.setText(entrenamiento.getVuelta());
        setNuevaPalabra();

    }

    public VEntrenamiento(VAdmin vAdmin, Jugador jugador, int numPal, Almacen_Palabras aPalabras) {
        initComponents();
        this.setLocationRelativeTo(vAdmin);

        JFrame jFrame;

        this.vAdmin = vAdmin;

        this.aPalabras = aPalabras;

        entrenamiento = new Entrenamiento(jugador, numPal, aPalabras);

        tNombreJ.setText(jugador.getNombre());
        tPuntos.setText(String.valueOf(jugador.getPuntos()));
        tFallos.setText("0");
        tPuntosPartida.setText("0");

        tVueltas.setText(entrenamiento.getVuelta());
        setNuevaPalabra();

    }

    public void cargarAlmacenPalabras(Almacen_Palabras aPalabras) {
        this.aPalabras = aPalabras;
    }

    public VEntrenamiento(VJugador vJugador, Administrador jugador) {
        initComponents();

        this.vJugador = vJugador;
        this.administrador = jugador;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRespuesta = new javax.swing.JLabel();
        spMostrarPalabra = new javax.swing.JScrollPane();
        tMostrarPalabra = new javax.swing.JTextArea();
        bEnviarRespuesta = new javax.swing.JButton();
        tRespuesta = new javax.swing.JTextField();
        tVueltas = new javax.swing.JTextField();
        jVueltas = new javax.swing.JLabel();
        jJugador = new javax.swing.JLabel();
        tNombreJ = new javax.swing.JTextField();
        jFallos = new javax.swing.JLabel();
        tFallos = new javax.swing.JTextField();
        jPuntos = new javax.swing.JLabel();
        tPuntos = new javax.swing.JTextField();
        jPista = new javax.swing.JLabel();
        tPista = new javax.swing.JTextField();
        bPedirPista = new javax.swing.JButton();
        iSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        iCabecera = new javax.swing.JLabel();
        bComprarPalabra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tComprarPalabra = new javax.swing.JTextField();
        jPuntos1 = new javax.swing.JLabel();
        tPuntosPartida = new javax.swing.JTextField();
        iFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRespuesta.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRespuesta.setText("Respuesta:");
        getContentPane().add(jRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        tMostrarPalabra.setColumns(20);
        tMostrarPalabra.setRows(5);
        spMostrarPalabra.setViewportView(tMostrarPalabra);

        getContentPane().add(spMostrarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 330, 400));

        bEnviarRespuesta.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bEnviarRespuesta.setText("Enviar respuesta");
        bEnviarRespuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEnviarRespuestaMouseClicked(evt);
            }
        });
        getContentPane().add(bEnviarRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 300, 30));

        tRespuesta.setBackground(new java.awt.Color(102, 102, 102));
        tRespuesta.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        tRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRespuestaActionPerformed(evt);
            }
        });
        getContentPane().add(tRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 300, 30));

        tVueltas.setEditable(false);
        tVueltas.setBackground(new java.awt.Color(102, 102, 102));
        tVueltas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tVueltas.setForeground(new java.awt.Color(255, 255, 255));
        tVueltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tVueltasActionPerformed(evt);
            }
        });
        getContentPane().add(tVueltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 300, 30));

        jVueltas.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jVueltas.setText("Vueltas:");
        getContentPane().add(jVueltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jJugador.setText("Jugador:");
        getContentPane().add(jJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        tNombreJ.setEditable(false);
        tNombreJ.setBackground(new java.awt.Color(102, 102, 102));
        tNombreJ.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tNombreJ.setForeground(new java.awt.Color(255, 255, 255));
        tNombreJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreJActionPerformed(evt);
            }
        });
        getContentPane().add(tNombreJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 300, 30));

        jFallos.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jFallos.setText("Fallos:");
        getContentPane().add(jFallos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        tFallos.setEditable(false);
        tFallos.setBackground(new java.awt.Color(102, 102, 102));
        tFallos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tFallos.setForeground(new java.awt.Color(255, 255, 255));
        tFallos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFallosActionPerformed(evt);
            }
        });
        getContentPane().add(tFallos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 300, 30));

        jPuntos.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPuntos.setText("Puntos:");
        getContentPane().add(jPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        tPuntos.setEditable(false);
        tPuntos.setBackground(new java.awt.Color(102, 102, 102));
        tPuntos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tPuntos.setForeground(new java.awt.Color(255, 255, 255));
        tPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPuntosActionPerformed(evt);
            }
        });
        getContentPane().add(tPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 300, 30));

        jPista.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPista.setText("Pista:");
        jPista.setToolTipText("");
        getContentPane().add(jPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 50, 30));

        tPista.setEditable(false);
        tPista.setBackground(new java.awt.Color(102, 102, 102));
        tPista.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tPista.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 300, 30));

        bPedirPista.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bPedirPista.setText("Pedir pista");
        bPedirPista.setActionCommand("jPedirPista");
        bPedirPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPedirPistaActionPerformed(evt);
            }
        });
        getContentPane().add(bPedirPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 300, 30));

        iSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Boton_salir.png"))); // NOI18N
        iSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSalirMouseClicked(evt);
            }
        });
        getContentPane().add(iSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Entrenamiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        iCabecera.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        iCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Cabecera.png"))); // NOI18N
        iCabecera.setToolTipText("");
        iCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                iCabeceraMouseDragged(evt);
            }
        });
        iCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(iCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 830, -1));

        bComprarPalabra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bComprarPalabra.setText("Comprar palabra");
        bComprarPalabra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bComprarPalabraMouseClicked(evt);
            }
        });
        getContentPane().add(bComprarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 300, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Palabra:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        tComprarPalabra.setEditable(false);
        tComprarPalabra.setBackground(new java.awt.Color(102, 102, 102));
        tComprarPalabra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tComprarPalabra.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tComprarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 300, 30));

        jPuntos1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPuntos1.setText("Puntos partida:");
        getContentPane().add(jPuntos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        tPuntosPartida.setEditable(false);
        tPuntosPartida.setBackground(new java.awt.Color(102, 102, 102));
        tPuntosPartida.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tPuntosPartida.setForeground(new java.awt.Color(255, 255, 255));
        tPuntosPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPuntosPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(tPuntosPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 300, 30));

        iFondo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        iFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/489.jpg"))); // NOI18N
        getContentPane().add(iFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 523));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSalirMouseClicked
        // TODO add your handling code here:
        VExitConfirmacionPartida vExit = new VExitConfirmacionPartida(this);
        this.setVisible(false);
        vExit.setVisible(true);
    }//GEN-LAST:event_iSalirMouseClicked

    private void iCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_iCabeceraMouseDragged

    private void iCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_iCabeceraMousePressed

    private void tNombreJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreJActionPerformed

    private void tPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPuntosActionPerformed

    private void tRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRespuestaActionPerformed

    private void bPedirPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPedirPistaActionPerformed
        // TODO add your handling code here:
        tPista.setText(entrenamiento.mostrarPista(entrenamiento.posPalabraActual()));
    }//GEN-LAST:event_bPedirPistaActionPerformed

    private void tPuntosPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPuntosPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPuntosPartidaActionPerformed

    private void bEnviarRespuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEnviarRespuestaMouseClicked
        // TODO add your handling code here:
        String respuesta = tRespuesta.getText();
        boolean acierto = respuesta.equalsIgnoreCase(palabraActual.getPalabra());
        boolean aplazada = palabraActual.isAplazada();
        int vueltaActual = Integer.parseInt(entrenamiento.getVuelta());

        if (acierto) {
            JFrame jf = new JFrame();
            JOptionPane.showMessageDialog(jf, "Palabra acertada.");

            tPuntosPartida.setText(entrenamiento.acertar());

            palabraActual.setAcertada(true);
            tRespuesta.setText("");

        }
        if (respuesta.equals("paso") && vueltaActual == 1) {
            JFrame jf = new JFrame();
            JOptionPane.showMessageDialog(jf, "Palabra aplazada.");

            palabraActual.setAplazada(true);
            aplazada = palabraActual.isAplazada();
        }
        if (!acierto && !aplazada) {
            JFrame jf = new JFrame();
            JOptionPane.showMessageDialog(jf, "Palabra fallada.");

            tFallos.setText(entrenamiento.fallar());

            palabraActual.setFallada(true);
            tRespuesta.setText("");
        }

        tPista.setText("");
        tComprarPalabra.setText("");

        boolean partidaTerminada;
        partidaTerminada = checkGanarPartida();
        partidaTerminada = checkPerderPartida();

        if (!partidaTerminada) {
            if (!vueltasFin()) {
                setNuevaPalabra();
            }
        }


    }//GEN-LAST:event_bEnviarRespuestaMouseClicked

    private boolean checkGanarPartida() {
        int puntosActuales = entrenamiento.getIntAciertos();
        int numPal = entrenamiento.getNumPal();
        if (puntosActuales == numPal) {
            JFrame jf = new JFrame();
            JOptionPane.showMessageDialog(jf, "Has ganado.");

            this.setVisible(false);
            if (vJugador == null) {
                vAdmin.setVisible(true);
            } else {
                vJugador.setVisible(true);
            }
            return true;
        }
        return false;
    }

    private boolean checkPerderPartida() {

        int todosPuntos = entrenamiento.getIntAciertos() + entrenamiento.getIntFallos();
        int fallos = entrenamiento.getIntFallos();
        int numPal = entrenamiento.getNumPal();
        if (todosPuntos == numPal && (fallos != 0)) {
            JFrame jf = new JFrame();
            JOptionPane.showMessageDialog(jf, "Has fallado " + entrenamiento.getFallos() + " palabras.");

            this.setVisible(false);

            if (vJugador == null) {
                vAdmin.setVisible(true);
            } else {
                vJugador.setVisible(true);
            }
            return true;
        }
        return false;
    }

    private void setNuevaPalabra() {
        int numPal = entrenamiento.getNumPal();
        do {
            entrenamiento.setPosPalabraActual(entrenamiento.posPalabraActual() + 1);
            if (entrenamiento.posPalabraActual() == numPal) {
                entrenamiento.setPosPalabraActual(0);
                String nuevaVuelta = entrenamiento.sumarVuelta();
                int nuevaIntVuelta = Integer.parseInt(nuevaVuelta);
                tVueltas.setText(nuevaVuelta);

            }
            palabraActual = entrenamiento.devolverPalabraActual(entrenamiento.posPalabraActual());
        } while (palabraActual.isAcertada() || palabraActual.isFallada());

        String palabra = palabraActual.adivinarPalabra();
        tMostrarPalabra.setText(palabra);
    }

    private boolean vueltasFin() {
        int nuevaIntVuelta = Integer.parseInt(tVueltas.getText());
        if (nuevaIntVuelta == 3) {

            JFrame jf = new JFrame();
            JOptionPane.showMessageDialog(jf, "La partida ha terminado.");

            this.setVisible(false);
            vJugador.setVisible(true);
            return true;
        }
        return false;
    }
    private void tVueltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tVueltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tVueltasActionPerformed

    private void tFallosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFallosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFallosActionPerformed

    private void bComprarPalabraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bComprarPalabraMouseClicked
        // TODO add your handling code here:
        tComprarPalabra.setText(entrenamiento.comprarPalabra(entrenamiento.posPalabraActual()));
    }//GEN-LAST:event_bComprarPalabraMouseClicked
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("GUI_Images/icono.png"));
        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComprarPalabra;
    private javax.swing.JButton bEnviarRespuesta;
    private javax.swing.JButton bPedirPista;
    private javax.swing.JLabel iCabecera;
    private javax.swing.JLabel iFondo;
    private javax.swing.JLabel iSalir;
    private javax.swing.JLabel jFallos;
    private javax.swing.JLabel jJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jPista;
    private javax.swing.JLabel jPuntos;
    private javax.swing.JLabel jPuntos1;
    private javax.swing.JLabel jRespuesta;
    private javax.swing.JLabel jVueltas;
    private javax.swing.JScrollPane spMostrarPalabra;
    private javax.swing.JTextField tComprarPalabra;
    private javax.swing.JTextField tFallos;
    private javax.swing.JTextArea tMostrarPalabra;
    private javax.swing.JTextField tNombreJ;
    private javax.swing.JTextField tPista;
    private javax.swing.JTextField tPuntos;
    private javax.swing.JTextField tPuntosPartida;
    private javax.swing.JTextField tRespuesta;
    private javax.swing.JTextField tVueltas;
    // End of variables declaration//GEN-END:variables
}
