package GUI;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author a.tercero.2020
 */
import Almacenes.*;
import java.awt.Image;
import java.awt.Toolkit;

public class VExit extends javax.swing.JFrame {

    int x;
    int y;

    VAdmin vAdmin;
    VJugador vJugador;
    VLogin vLogin;

    Almacen_Palabras aPalabras;
    Almacen_Partidas aPartidas;
    Almacen_Jugadores aJugadores;

    /**
     * Creates new form VExit
     */
    public VExit(VLogin vLogin, Almacen_Palabras aPalabras, Almacen_Partidas aPartidas, Almacen_Jugadores aJugadores) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.vLogin = vLogin;

        this.aPalabras = aPalabras;
        this.aPartidas = aPartidas;
        this.aJugadores = aJugadores;

    }

    public VExit(VJugador vJugador, Almacen_Palabras aPalabras, Almacen_Partidas aPartidas, Almacen_Jugadores aJugadores) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.vJugador = vJugador;

        this.aPalabras = aPalabras;
        this.aPartidas = aPartidas;
        this.aJugadores = aJugadores;
    }

    public VExit(VAdmin vAdmin, Almacen_Palabras aPalabras, Almacen_Partidas aPartidas, Almacen_Jugadores aJugadores) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.vAdmin = vAdmin;

        this.aPalabras = aPalabras;
        this.aPartidas = aPartidas;
        this.aJugadores = aJugadores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGuardarPalabras = new javax.swing.JButton();
        iSalir = new javax.swing.JLabel();
        iCabecera = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tGuardarPalabras = new javax.swing.JTextField();
        bGuardarJugadores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tGuardarJugadores = new javax.swing.JTextField();
        bGuardarPartidas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tGuardarPartidas = new javax.swing.JTextField();
        bSalir = new javax.swing.JButton();
        iFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bGuardarPalabras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bGuardarPalabras.setText("Guardar almacen de Palabras");
        bGuardarPalabras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGuardarPalabrasMouseClicked(evt);
            }
        });
        bGuardarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarPalabrasActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardarPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 270, -1));

        iSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Boton_salir.png"))); // NOI18N
        iSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSalirMouseClicked(evt);
            }
        });
        getContentPane().add(iSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        iCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Cabecera.png"))); // NOI18N
        iCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                iCabeceraMouseDragged(evt);
            }
        });
        iCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(iCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Nombre del Archivo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        tGuardarPalabras.setBackground(new java.awt.Color(102, 102, 102));
        tGuardarPalabras.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        tGuardarPalabras.setForeground(new java.awt.Color(255, 255, 255));
        tGuardarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tGuardarPalabrasActionPerformed(evt);
            }
        });
        getContentPane().add(tGuardarPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, -1));

        bGuardarJugadores.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bGuardarJugadores.setText("Guardar almacen de Jugadores");
        bGuardarJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGuardarJugadoresMouseClicked(evt);
            }
        });
        getContentPane().add(bGuardarJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 270, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Nombre del Archivo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        tGuardarJugadores.setBackground(new java.awt.Color(102, 102, 102));
        tGuardarJugadores.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        tGuardarJugadores.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tGuardarJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 170, -1));

        bGuardarPartidas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bGuardarPartidas.setText("Guardar almacen de Partidas");
        bGuardarPartidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bGuardarPartidasMouseClicked(evt);
            }
        });
        getContentPane().add(bGuardarPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 270, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("Nombre del Archivo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        tGuardarPartidas.setBackground(new java.awt.Color(102, 102, 102));
        tGuardarPartidas.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        tGuardarPartidas.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tGuardarPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 170, -1));

        bSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        bSalir.setText("Salir");
        bSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalirMouseClicked(evt);
            }
        });
        getContentPane().add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 210, -1));

        iFondo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        iFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/489.jpg"))); // NOI18N
        getContentPane().add(iFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_iCabeceraMouseDragged

    private void iCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_iCabeceraMousePressed

    private void iSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        if (vLogin != null) {
            vLogin.setVisible(true);
        }
        if (vAdmin != null) {
            vAdmin.setVisible(true);
        }
        if (vJugador != null) {
            vJugador.setVisible(true);
        }

    }//GEN-LAST:event_iSalirMouseClicked

    private void bGuardarPalabrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGuardarPalabrasMouseClicked
        // TODO add your handling code here:
        String current = tGuardarPalabras.getText();

        char[] array = current.toCharArray();

        if (array.length >= 4) {
            char ultima = array[array.length - 1];
            String ultimaS = String.valueOf(ultima);
            char penultima = array[array.length - 2];
            String penultimaS = String.valueOf(penultima);
            char antepenultima = array[array.length - 3];
            String antepenultimaS = String.valueOf(antepenultima);
            char anterior = array[array.length - 4];
            String anteriorS = String.valueOf(anterior);

            if (ultimaS.equals("r") && penultimaS.equals("e") && antepenultimaS.equals("s") && anteriorS.equals(".")) {
                aPalabras.guardarAlmacen(current);
            } else {
                current += ".ser";
                aPalabras.guardarAlmacen(current);
            }

        } else {
            current += ".ser";
            aPalabras.guardarAlmacen(current);
        }


    }//GEN-LAST:event_bGuardarPalabrasMouseClicked

    private void bGuardarJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGuardarJugadoresMouseClicked
        // TODO add your handling code here:
        String current = tGuardarJugadores.getText();

        char[] array = current.toCharArray();

        if (array.length >= 4) {
            char ultima = array[array.length - 1];
            String ultimaS = String.valueOf(ultima);
            char penultima = array[array.length - 2];
            String penultimaS = String.valueOf(penultima);
            char antepenultima = array[array.length - 3];
            String antepenultimaS = String.valueOf(antepenultima);
            char anterior = array[array.length - 4];
            String anteriorS = String.valueOf(anterior);

            if (ultimaS.equals("r") && penultimaS.equals("e") && antepenultimaS.equals("s") && anteriorS.equals(".")) {
                aJugadores.guardarAlmacen(current);
            } else {
                current += ".ser";
                aJugadores.guardarAlmacen(current);
            }

        } else {
            current += ".ser";
            aJugadores.guardarAlmacen(current);
        }
    }//GEN-LAST:event_bGuardarJugadoresMouseClicked

    private void bGuardarPartidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bGuardarPartidasMouseClicked
        // TODO add your handling code here:
        String current = tGuardarPartidas.getText();

        char[] array = current.toCharArray();

        if (array.length >= 4) {
            char ultima = array[array.length - 1];
            String ultimaS = String.valueOf(ultima);
            char penultima = array[array.length - 2];
            String penultimaS = String.valueOf(penultima);
            char antepenultima = array[array.length - 3];
            String antepenultimaS = String.valueOf(antepenultima);
            char anterior = array[array.length - 4];
            String anteriorS = String.valueOf(anterior);

            if (ultimaS.equals("r") && penultimaS.equals("e") && antepenultimaS.equals("s") && anteriorS.equals(".")) {
                aPartidas.guardarAlmacen(current);
            } else {
                current += ".ser";
                aPartidas.guardarAlmacen(current);
            }

        } else {
            current += ".ser";
            aPartidas.guardarAlmacen(current);
        }
    }//GEN-LAST:event_bGuardarPartidasMouseClicked

    private void bSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSalirMouseClicked

    private void bGuardarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarPalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bGuardarPalabrasActionPerformed

    private void tGuardarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tGuardarPalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tGuardarPalabrasActionPerformed

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("GUI_Images/icono.png"));
        return retValue;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardarJugadores;
    private javax.swing.JButton bGuardarPalabras;
    private javax.swing.JButton bGuardarPartidas;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel iCabecera;
    private javax.swing.JLabel iFondo;
    private javax.swing.JLabel iSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tGuardarJugadores;
    private javax.swing.JTextField tGuardarPalabras;
    private javax.swing.JTextField tGuardarPartidas;
    // End of variables declaration//GEN-END:variables
}
