/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Almacenes.Almacen_Jugadores;
import Almacenes.Almacen_Palabras;
import Almacenes.Almacen_Partidas;
import Personas.Administrador;
import Personas.Historial;
import Personas.Jugador;
import Tipos_de_Juego.Partida;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author e.tamajon.2020
 */
public class VJugador extends javax.swing.JFrame {

    int x, y;
    Jugador jugador;
    Administrador admin;

    VLogin vLogin;
    VPartida vPartida;
    VEntrenamiento vEntrenamiento;

    Almacen_Jugadores aJugadores;
    Almacen_Palabras aPalabras;
    Almacen_Partidas aPartidas;

    boolean otroUser;

    /**
     * Creates new form VJugador
     *
     * @param vLogin
     * @param jugador
     */
    public VJugador(VLogin vLogin, Jugador jugador, Administrador admin,
            Almacen_Jugadores aJugadores, Almacen_Palabras aPalabras,
            Almacen_Partidas aPartidas) {
        initComponents();

        this.vLogin = vLogin;
        this.setLocationRelativeTo(vLogin);
        this.jugador = jugador;
        this.admin = admin;

        this.aJugadores = aJugadores;
        this.aPalabras = aPalabras;
        this.aPartidas = aPartidas;

        tNombre.setText(jugador.getNombre());
        tPuntosJugador.setText(String.valueOf(jugador.getPuntos()));

        tNombre.setEditable(false);
        tPuntosJugador.setEditable(false);
    }

    public boolean checkInputError(int rango, String respuestaUsuario) {

        int posicion = 1;
        boolean errorInput = false;

        char[] chars = respuestaUsuario.toCharArray();
        for (int i = 0; i < chars.length; i++) {
            if (chars[i] == '1' || chars[i] == '2' || chars[i] == '3' || chars[i] == '4' || chars[i] == '5' || chars[i] == '6' || chars[i] == '7' || chars[i] == '8' || chars[i] == '9' || chars[i] == '0') {
                errorInput = false;
            } else {

                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Debes introducir un valor numérico entre 1 y " + (rango));
                errorInput = true;
                break;
            }
        }
        if (!errorInput) {
            posicion = Integer.parseInt(respuestaUsuario);
            if (posicion < 1 || posicion > (rango)) {
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Debes introducir un valor numérico entre 1 y " + (rango));
                errorInput = true;
            }
        }

        return errorInput;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spConsolaJugador = new javax.swing.JScrollPane();
        tConsolaJugador = new javax.swing.JTextArea();
        jNombreJugador = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jPuntosJugador = new javax.swing.JLabel();
        tPuntosJugador = new javax.swing.JTextField();
        jNumPal = new javax.swing.JLabel();
        tNumPal = new javax.swing.JTextField();
        jOtroUsuario = new javax.swing.JLabel();
        tOtroUsuario = new javax.swing.JTextField();
        jOtraPass = new javax.swing.JLabel();
        tOtraPass = new javax.swing.JTextField();
        bJugar = new javax.swing.JButton();
        bJugarEntrenamiento = new javax.swing.JButton();
        bHistorial = new javax.swing.JButton();
        bCerrarSesion = new javax.swing.JButton();
        iSalir = new javax.swing.JLabel();
        iCabecera = new javax.swing.JLabel();
        iFondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setMinimumSize(new java.awt.Dimension(820, 520));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tConsolaJugador.setColumns(20);
        tConsolaJugador.setRows(5);
        spConsolaJugador.setViewportView(tConsolaJugador);

        getContentPane().add(spConsolaJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 350, 330));

        jNombreJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jNombreJugador.setText("Nombre:");
        getContentPane().add(jNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        tNombre.setBackground(new java.awt.Color(102, 102, 102));
        tNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 270, 30));

        jPuntosJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jPuntosJugador.setText("Puntos:");
        getContentPane().add(jPuntosJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        tPuntosJugador.setBackground(new java.awt.Color(102, 102, 102));
        tPuntosJugador.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tPuntosJugador.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tPuntosJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 270, 30));

        jNumPal.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jNumPal.setText("N. Palabras:");
        getContentPane().add(jNumPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        tNumPal.setBackground(new java.awt.Color(102, 102, 102));
        tNumPal.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tNumPal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tNumPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 270, 30));

        jOtroUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jOtroUsuario.setText("Usuario:");
        getContentPane().add(jOtroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        tOtroUsuario.setBackground(new java.awt.Color(102, 102, 102));
        tOtroUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tOtroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tOtroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 270, 30));

        jOtraPass.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jOtraPass.setText("Contraseña:");
        getContentPane().add(jOtraPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        tOtraPass.setBackground(new java.awt.Color(102, 102, 102));
        tOtraPass.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tOtraPass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tOtraPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 270, 30));

        bJugar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bJugar.setText("Jugar partida");
        bJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bJugarMouseClicked(evt);
            }
        });
        getContentPane().add(bJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 370, -1));

        bJugarEntrenamiento.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bJugarEntrenamiento.setText("Jugar entrenamiento");
        bJugarEntrenamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bJugarEntrenamientoMouseClicked(evt);
            }
        });
        getContentPane().add(bJugarEntrenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 370, -1));

        bHistorial.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bHistorial.setText("Ver historial");
        bHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHistorialMouseClicked(evt);
            }
        });
        getContentPane().add(bHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 370, -1));

        bCerrarSesion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bCerrarSesion.setText("Cerrar sesión");
        bCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(bCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 370, -1));

        iSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Boton_salir.png"))); // NOI18N
        iSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSalirMouseClicked(evt);
            }
        });
        getContentPane().add(iSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        iCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Cabecera.png"))); // NOI18N
        iCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                iCabeceraMouseDragged(evt);
            }
        });
        iCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(iCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 830, -1));

        iFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/489.jpg"))); // NOI18N
        getContentPane().add(iFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSalirMouseClicked
        // TODO add your handling code here:
        VExit vExit = new VExit(this, aPalabras, aPartidas, aJugadores);
        this.setVisible(false);
        vExit.setVisible(true);
    }//GEN-LAST:event_iSalirMouseClicked

    private void iCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_iCabeceraMouseDragged

    private void iCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_iCabeceraMousePressed

    private void bCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarSesionMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        vLogin.setLocationRelativeTo(this);
        vLogin.setVisible(true);
    }//GEN-LAST:event_bCerrarSesionMouseClicked

    private void bHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHistorialMouseClicked
        // TODO add your handling code here:
        Historial historial = jugador.getHistorial();
        String showHistorial = historial.toString();

        tConsolaJugador.setText(showHistorial);
    }//GEN-LAST:event_bHistorialMouseClicked

    private void bJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bJugarMouseClicked
        JFrame jFrame;
        if (!otroUser) {
            jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Es necesario iniciar sesión con otro usuario.");
        }
        otroUser = true;

        String user = tOtroUsuario.getText();
        String password = tOtraPass.getText();

        boolean vacio = tNumPal.getText().equals("");

        String respuestaUsuario = tNumPal.getText();

        if (user.equals(admin.getNombre()) && password.equals(admin.getContraseña())) {

            if (!vacio) {
                if (!checkInputError(24, respuestaUsuario)) {
                    int numPal = Integer.parseInt(respuestaUsuario);

                    if (!aPalabras.esVacio(numPal)) {
                        jFrame = new JFrame();
                        JOptionPane.showMessageDialog(jFrame, "Vas a jugar contra el admin.");

                        Partida partida = new Partida(jugador, new Jugador(admin), numPal, aPalabras);
                        tNumPal.setText("");
                        initPartida(partida);
                    } else {
                        jFrame = new JFrame();
                        JOptionPane.showMessageDialog(jFrame, "No hay palabras suficientes. Ingrese como administrador y cree nuevas palabras."
                                + "Recuerde que debe de haber letras desde la a, hasta la letra con la que desee jugar.");
                    }

                } else {
                    jFrame = new JFrame();
                    JOptionPane.showMessageDialog(jFrame, "Inserte un valor numerico entre 1 y 24");
                }
            } else {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Rellene el campo de palabras.");
            }
        }

        if (aJugadores.checkUser(user, password)) {
            if (!vacio) {

                if (!checkInputError(24, respuestaUsuario)) {
                    int numPal = Integer.parseInt(respuestaUsuario);

                    Jugador jugadorSel = aJugadores.selectJugador(user, password);
                    Partida partida = new Partida(jugador, jugadorSel, numPal, aPalabras);
                    tNumPal.setText("");
                    initPartida(partida);

                } else {
                    jFrame = new JFrame();
                    JOptionPane.showMessageDialog(jFrame, "Inserte un valor numerico entre 1 y 24");
                }
            } else {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Rellene el campo de palabras.");
            }
        } else {
            jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "El jugador no esta registrado");

        }


    }//GEN-LAST:event_bJugarMouseClicked

    private void initPartida(Partida partida) {
        if (partida.checkJugar()) {
            this.setVisible(false);
            vPartida = new VPartida(partida, aPalabras, aPartidas, this);
            vPartida.setVisible(true);
        } else {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Uno de los dos jugadores no tiene puntos suficientes.");
        }
    }

    private void bJugarEntrenamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bJugarEntrenamientoMouseClicked
        // TODO add your handling code here:

        JFrame jFrame;
        String respuestaUsuario = tNumPal.getText();
        boolean vacio = tNumPal.getText().equals("");

        if (!vacio) {
            if (!checkInputError(24, respuestaUsuario)) {
                int numPal = Integer.parseInt(respuestaUsuario);

                if (!aPalabras.esVacio(numPal)) {
                    vEntrenamiento = new VEntrenamiento(this, new Jugador(admin), numPal, aPalabras);
                    tNumPal.setText("");
                    this.setVisible(false);
                    vEntrenamiento.setVisible(true);
                } else {
                    jFrame = new JFrame();
                    JOptionPane.showMessageDialog(jFrame, "No hay palabras suficientes. Ingrese como administrador y cree nuevas palabras."
                            + "Recuerde que debe de haber letras desde la a, hasta la letra con la que desee jugar.");
                }

            } else {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Inserte un valor numerico entre 1 y 24");
            }
        } else {
            jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Rellene el campo de palabras.");
        }

    }//GEN-LAST:event_bJugarEntrenamientoMouseClicked

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("GUI_Images/icono.png"));
        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCerrarSesion;
    private javax.swing.JButton bHistorial;
    private javax.swing.JButton bJugar;
    private javax.swing.JButton bJugarEntrenamiento;
    private javax.swing.JLabel iCabecera;
    private javax.swing.JLabel iFondo;
    private javax.swing.JLabel iSalir;
    private javax.swing.JLabel jNombreJugador;
    private javax.swing.JLabel jNumPal;
    private javax.swing.JLabel jOtraPass;
    private javax.swing.JLabel jOtroUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPuntosJugador;
    private javax.swing.JScrollPane spConsolaJugador;
    private javax.swing.JTextArea tConsolaJugador;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tNumPal;
    private javax.swing.JTextField tOtraPass;
    private javax.swing.JTextField tOtroUsuario;
    private javax.swing.JTextField tPuntosJugador;
    // End of variables declaration//GEN-END:variables
}
