/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Almacenes.*;
import Personas.Administrador;
import Personas.Jugador;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author e.tamajon.2020
 */
public class VLogin extends javax.swing.JFrame {

    int x, y;
    Almacen_Jugadores aJugadores;
    Almacen_Palabras aPalabras;
    Almacen_Partidas aPartidas;

    Administrador admin;
    Jugador jugador;

    boolean esAdmin = false;
    boolean hayAdmin = false;

    VJugador vJugador;
    VAdmin vAdmin;

    /**
     * Creates new form VLogin
     */
    public VLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        aJugadores = new Almacen_Jugadores();
        aPalabras = new Almacen_Palabras();
        aPartidas = new Almacen_Partidas();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("GUI_Images/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUser = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JLabel();
        tPassword = new javax.swing.JTextField();
        jRegistrarse = new javax.swing.JButton();
        jLogin = new javax.swing.JButton();
        jCargar = new javax.swing.JButton();
        jJugadores = new javax.swing.JLabel();
        tJugadores = new javax.swing.JTextField();
        jCargarPalabras = new javax.swing.JButton();
        jPalabras = new javax.swing.JLabel();
        tPalabras = new javax.swing.JTextField();
        jCargarPartidas = new javax.swing.JButton();
        tPartida = new javax.swing.JTextField();
        jPartidas = new javax.swing.JLabel();
        jConfirmarAdmin = new javax.swing.JRadioButton();
        jMiembros = new javax.swing.JLabel();
        iSalir = new javax.swing.JLabel();
        iCabecera = new javax.swing.JLabel();
        iURJC = new javax.swing.JLabel();
        iFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setMinimumSize(new java.awt.Dimension(820, 520));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUser.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jUser.setText("Usuario:");
        getContentPane().add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        tUser.setBackground(new java.awt.Color(102, 102, 102));
        tUser.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 490, 30));

        jPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jPassword.setText("Contraseña:");
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        tPassword.setBackground(new java.awt.Color(102, 102, 102));
        tPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tPassword.setForeground(new java.awt.Color(255, 255, 255));
        tPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 490, 30));

        jRegistrarse.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jRegistrarse.setText("Registrarse");
        jRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegistrarseMouseClicked(evt);
            }
        });
        getContentPane().add(jRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 130, 30));

        jLogin.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLogin.setText("Entrar");
        jLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginMouseClicked(evt);
            }
        });
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 90, 30));

        jCargar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCargar.setText("Cargar almacen de jugadores");
        jCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCargarMouseClicked(evt);
            }
        });
        jCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargarActionPerformed(evt);
            }
        });
        getContentPane().add(jCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 30));

        jJugadores.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jJugadores.setText("Almacen de jugadores:");
        getContentPane().add(jJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        tJugadores.setBackground(new java.awt.Color(102, 102, 102));
        tJugadores.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        tJugadores.setForeground(new java.awt.Color(255, 255, 255));
        tJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(tJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 470, 20));

        jCargarPalabras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCargarPalabras.setText("Cargar almacen de palabras");
        jCargarPalabras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCargarPalabrasMouseClicked(evt);
            }
        });
        jCargarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargarPalabrasActionPerformed(evt);
            }
        });
        getContentPane().add(jCargarPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 30));

        jPalabras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPalabras.setText("Almacen de palabras:");
        getContentPane().add(jPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        tPalabras.setBackground(new java.awt.Color(102, 102, 102));
        tPalabras.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        tPalabras.setForeground(new java.awt.Color(255, 255, 255));
        tPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPalabrasActionPerformed(evt);
            }
        });
        getContentPane().add(tPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 470, 20));

        jCargarPartidas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCargarPartidas.setText("Cargar almacen de partidas");
        jCargarPartidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCargarPartidasMouseClicked(evt);
            }
        });
        jCargarPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargarPartidasActionPerformed(evt);
            }
        });
        getContentPane().add(jCargarPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 230, 30));

        tPartida.setBackground(new java.awt.Color(102, 102, 102));
        tPartida.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        tPartida.setForeground(new java.awt.Color(255, 255, 255));
        tPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(tPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 310, 20));

        jPartidas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPartidas.setText("Almacen de partidas:");
        getContentPane().add(jPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jConfirmarAdmin.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jConfirmarAdmin.setText("¿Eres admin?");
        jConfirmarAdmin.setContentAreaFilled(false);
        jConfirmarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jConfirmarAdminMouseClicked(evt);
            }
        });
        getContentPane().add(jConfirmarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 160, 40));

        jMiembros.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jMiembros.setText("Andrés Gonzalez Antohi, Enrique Tamajón Castilla, Alexander Tercero Moreno");
        getContentPane().add(jMiembros, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        iSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Boton_salir.png"))); // NOI18N
        iSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSalirMouseClicked(evt);
            }
        });
        getContentPane().add(iSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        iCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Cabecera.png"))); // NOI18N
        iCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                iCabeceraMouseDragged(evt);
            }
        });
        iCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(iCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 830, -1));

        iURJC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/Logo_URJC.png"))); // NOI18N
        iURJC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iURJCMouseClicked(evt);
            }
        });
        getContentPane().add(iURJC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        iFondo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        iFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Images/489.jpg"))); // NOI18N
        getContentPane().add(iFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 523));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPasswordActionPerformed

    private void iCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_iCabeceraMousePressed

    private void iCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCabeceraMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_iCabeceraMouseDragged

    private void iSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSalirMouseClicked
        // TODO add your handling code here:
        VExit vExit = new VExit(this, aPalabras, aPartidas, aJugadores);
        this.setVisible(false);
        vExit.setVisible(true);
    }//GEN-LAST:event_iSalirMouseClicked

    private void iURJCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iURJCMouseClicked
        String enlaceInternet = "https://www.urjc.es";
        Desktop enlace = Desktop.getDesktop();
        try {
            enlace.browse(new URI(enlaceInternet));
        } catch (URISyntaxException ex) {
            Logger.getLogger(VLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iURJCMouseClicked

    private void jCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCargarActionPerformed

    private void jCargarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargarPalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCargarPalabrasActionPerformed

    private void jCargarPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargarPartidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCargarPartidasActionPerformed

    private void tJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJugadoresActionPerformed

    private void tPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPalabrasActionPerformed

    private void tPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPartidaActionPerformed

    private void jCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCargarMouseClicked

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        try {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();

            aJugadores = aJugadores.cargarAlmacen(ruta);
            if (aJugadores == null) {
                tJugadores.setText("Archivo inválido.");
            } else {
                tJugadores.setText(ruta);
            }

        } catch (NullPointerException e) {
            tJugadores.setText("No se ha seleccionado ningún fichero");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jCargarMouseClicked

    private void jCargarPalabrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCargarPalabrasMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        try {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();

            aPalabras = aPalabras.cargarAlmacen(ruta);
            if (aPalabras == null) {
                tPalabras.setText("Archivo inválido.");
            } else {
                tPalabras.setText(ruta);
            }

        } catch (NullPointerException e) {
            tPalabras.setText("No se ha seleccionado ningún fichero");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jCargarPalabrasMouseClicked

    private void jCargarPartidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCargarPartidasMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(fileChooser);
        try {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            aPartidas = aPartidas.cargarAlmacen(ruta);
            if (aPartidas == null) {
                tPartida.setText("Archivo inválido.");
            } else {
                tPartida.setText(ruta);
            }
        } catch (NullPointerException e) {
            tPartida.setText("No se ha seleccionado ningún fichero");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jCargarPartidasMouseClicked

    private void jLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginMouseClicked
        String user = tUser.getText();
        String password = tPassword.getText();
        JFrame jFrame;
        boolean accedido = false;

        if (!hayAdmin) {
            jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Es necesario crear un administrador primero.");
        } else {
            if (user.equals(admin.getNombre()) && password.equals(admin.getContraseña()) && esAdmin) {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Accedes admin.");
                accedido = true;

                jugador = aJugadores.selectJugador(user, password);

                vAdmin = new VAdmin(this, admin, aJugadores, aPalabras, aPartidas);
                this.setVisible(false);
                vAdmin.setVisible(true);
            }

            if (user.equals(admin.getNombre()) && password.equals(admin.getContraseña()) && !esAdmin) {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "El jugador que desea entrar es admin. Por favor, seleccione la opción correspondiente.");
                accedido = true;

            }

            if (aJugadores.checkUser(user, password) && !esAdmin) {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Accedes jugador.");
                accedido = true;

                jugador = aJugadores.selectJugador(user, password);

                vJugador = new VJugador(this, jugador, admin, aJugadores, aPalabras, aPartidas);
                this.setVisible(false);
                vJugador.setVisible(true);
            }

            if (aJugadores.checkUser(user, password) && esAdmin) {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "El jugador que desea acceder no es admin. Deseleccione la opción correspondiente.");
                accedido = true;
            }

            if (!accedido) {
                tUser.setText("");
                tPassword.setText("");
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Usuario y contraseña erróneos.");
            }
        }
    }//GEN-LAST:event_jLoginMouseClicked

    private void jRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegistrarseMouseClicked
        // TODO add your handling code here:

        JFrame jFrame;
        boolean vacio = ((tUser.getText().equals("")) && (tPassword.getText().equals("")));

        String user = tUser.getText();
        String password = tPassword.getText();

        if (!hayAdmin) {
            if (!vacio && esAdmin) {
                admin = new Administrador(user, password);
                hayAdmin = true;
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Admin creado.");
            }
            if (!vacio && !esAdmin) {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "El primer jugador creado ha de ser admin.");
            }
        } else {
            if (!vacio && !esAdmin) {

                Jugador jugador = new Jugador(user, password);

                if (!jugador.equalsWA(admin)) {
                    if (aJugadores.addJugador(jugador)) {
                        jFrame = new JFrame();
                        JOptionPane.showMessageDialog(jFrame, "Nuevo jugador creado con éxito.");

                    } else {
                        jFrame = new JFrame();
                        JOptionPane.showMessageDialog(jFrame, "Este jugador ya existia antes.");
                    }

                } else {
                    jFrame = new JFrame();
                    JOptionPane.showMessageDialog(jFrame, "Este jugador ya es el administrador.");
                }
            }

            if (!vacio && esAdmin) {
                jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Ya hay un admin creado, no se pueden crear mas en esta sesion");
            }
        }

        if (vacio) {
            jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Introduzca un nombre y una contraseña.");
        }


    }//GEN-LAST:event_jRegistrarseMouseClicked

    private void jConfirmarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConfirmarAdminMouseClicked
        // TODO add your handling code here:
        esAdmin = !esAdmin;
    }//GEN-LAST:event_jConfirmarAdminMouseClicked

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iCabecera;
    private javax.swing.JLabel iFondo;
    private javax.swing.JLabel iSalir;
    private javax.swing.JLabel iURJC;
    private javax.swing.JButton jCargar;
    private javax.swing.JButton jCargarPalabras;
    private javax.swing.JButton jCargarPartidas;
    private javax.swing.JRadioButton jConfirmarAdmin;
    private javax.swing.JLabel jJugadores;
    private javax.swing.JButton jLogin;
    private javax.swing.JLabel jMiembros;
    private javax.swing.JLabel jPalabras;
    private javax.swing.JLabel jPartidas;
    private javax.swing.JLabel jPassword;
    private javax.swing.JButton jRegistrarse;
    private javax.swing.JLabel jUser;
    private javax.swing.JTextField tJugadores;
    private javax.swing.JTextField tPalabras;
    private javax.swing.JTextField tPartida;
    private javax.swing.JTextField tPassword;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
